# consts.py
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part

FLAG_ROWS = 3
FLAG_COLS = 4

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

#screen
BACKGROUND_COLOR_BLINDMINES= (60, 179, 113)
GRASS_WIDTH=40
GRASS_HEIGHT=30

FLAG_SIZE= (FLAG_COLS * FLAG_ROWS) * CELL_SIZE
X_SIZE_FLAG = FLAG_COLS * CELL_SIZE
Y_SIZE_FLAG = FLAG_ROWS * CELL_SIZE