# consts.py
GRASS_IMAGE='bin/bin/grass.png'
FLAG_IMAGE='bin/bin/flag.png'
MINE_IMAGE='bin/bin/mine.png'
SOLDIER_IMAGE='bin/bin/soldier.png'
SOLDIER_NIGHT_IMAGE='bin/bin/soldier_night.png'
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

GRID_DURATION_MS=1000

#soldier
SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part
X_SIZE_SOLDIER = SOLDIER_COLS * CELL_SIZE
Y_SIZE_SOLDIER = SOLDIER_ROWS * CELL_SIZE
SOLDIER_START_LOC=[0,0]

FLAG_ROWS = 3
FLAG_COLS = 4
# game_field.py
flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3
X_SIZE_MINE= MINE_COLS * CELL_SIZE
Y_SIZE_MINE = MINE_ROWS * CELL_SIZE



MINE="MINE"
FREE="FREE"
FLAG="FLAG"
SOLDIER="SOLDIER"
#color
BLACK = (0, 0, 0)

#win or lose text
FONT_NAME = "Calibri"
LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = BLACK
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))
WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (89, 89, 89)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

RUNNING_STATE = 1
LOSE_STATE = 2
WIN_STATE = 3

#screen
BACKGROUND_COLOR_BLIND_MINES= (60, 179, 113)
BACKGROUND_COLOR_LASER_VISION= (0, 0, 0)
LASERS_COLOR=(238, 130, 238)
GRASS_WIDTH=30
GRASS_HEIGHT=30

FLAG_SIZE= (FLAG_COLS * FLAG_ROWS) * CELL_SIZE
X_SIZE_FLAG = FLAG_COLS * CELL_SIZE
Y_SIZE_FLAG = FLAG_ROWS * CELL_SIZE
